# Generated by Django 5.0.3 on 2024-03-26 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baloon',
            name='price_specifications',
            field=models.ForeignKey(help_text='Укажите цену для этого типа шарика.', on_delete=django.db.models.deletion.CASCADE, to='blog.pricebaloonspecifications', verbose_name='Цена характеристик'),
        ),
    ]
